name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
      - name: Hassfest
        uses: home-assistant/actions/hassfest@main
      - name: Tests
        run: |
          python -m pytest
